#!/bin/bash

# Set as required
# XCC=«path-to-cc65-repo»
# TGT=«target»
# EXT=«target-executable-extension»
# OUT=«target-filename-case-upper-or-lower»

XCC=~/Documents/development/cc65
TGT=cx16
EXT=prg
OUT=upper

if [[ ! -f ../flt-$TGT.lib ]] ; then
    echo "Build flt-$TGT.lib first!"
    exit
fi

xform() {
    local x="$1"

    if [[ $OUT == upper ]] ; then
        echo "${x^^}"
    else
        echo "${x,,}"
    fi
}

# Build averages and mandelfloat for target
for C in averages mandelfloat ; do
	php ../flt.php -i $C.c -o $C-flt.c -x "-I $XCC/include -I .."
	$XCC/bin/cc65 -t $TGT -I $XCC/include $C-flt.c
	$XCC/bin/ca65 -t $TGT $C-flt.s
	$XCC/bin/ld65 -o $(xform $C.$EXT) -t $TGT $C-flt.o -L .. flt-$TGT.lib -L $XCC/lib $TGT.lib
done

# Build flops for target
C=flops
php ../flt.php -i $C.c -o $C-flt.c -x "-D__${TGT^^}__ -I $XCC/include -I .."
$XCC/bin/cc65 -t $TGT -I $XCC/include $C-flt.c
$XCC/bin/ca65 -t $TGT $C-flt.s
$XCC/bin/ld65 -o $(xform $C.$EXT) -t $TGT $C-flt.o -L .. flt-$TGT.lib -L $XCC/lib $TGT.lib

# Build accuracy, tests, and paranoia for host
C=accuracy
gcc -o $C $C.c ../*.c -I .. -lm

C=tests
gcc -o $C $C.c ../*.c -I ..

C=paranoia
php ../flt.php -i $C.c -o $C-flt.c -x "-DNOSIGNAL -DSingle -I .."
gcc -o $C $C-flt.c ../*.c

# Clean up
rm *-flt.c *.s *.o
